### ISSUE TITLE
Create jupyter-notebook-based GUI

### ISSUE THREAD

**Issue by dafrose** [dafrose/knowviz#1]
### Concept

Use widget functionality of Jupyter notebooks to execute all relevant actions instead of a custom non-web GUI (previously: `kivi`).

### ToDos

- [ ] Button to create graph based on current selection (default: all)
- [ ] Button to select subgraph --> show more widgets
  - [ ] Drop-down menu to select nodes for subgraph (either adding one-by-one or multi-select)
  - [ ] Apply selection
- [ ] Drop-down menu (+ buttons) to select and open latex file/source file or PDF
  - possibly in separate tab
- [ ] Button to refresh (some) index
- [ ] Buttons to add new content/remove content?
