### ISSUE TITLE
Implement markdown-based documents

### ISSUE THREAD

**Issue by dafrose** [dafrose/knowviz#3]
I will switch the backend to [knowledge-repo](https://github.com/airbnb/knowledge-repo) which stores knowledge in markdown files. 

### ToDos:
- [ ] use html tag `<cite>someone-2001</cite>` to mark citations
- [ ] parse citations using bibtex library file to a form following [this suggestion](https://www.abhith.net/post/markdown-link-within-document/) 
- [ ] store additional info in YAML-based file header
